#!/bin/bash
LAYOUT=$($HOME/.config/suckless/xdotool/xkblayout-state/xkblayout-state print " %s (%c)" |grep il |wc -l)
if test $LAYOUT = "1"; then
    $HOME/.config/suckless/xdotool/cl.sh
    sleep 0.5
    xdotool type "| col-1 | col-2 | col-3 | --- | --- | --- | val1 | val2 | val3 |"
else
    sleep 0.5
    xdotool type "| col-1 | col-2 | col-3 | --- | --- | --- | val1 | val2 | val3 |"
fi
